import { DividerHorizontalIcon, ListBulletIcon } from "@radix-ui/react-icons";
import {
  BoldIcon,
  Code2Icon,
  Eye,
  EyeIcon,
  EyeOff,
  FileTextIcon,
  HeartIcon,
  Image,
  ItalicIcon,
  ListOrdered,
  Loader,
  MessageCircleMore,
  MoveLeftIcon,
  Pilcrow,
  PlusIcon,
  Quote,
  Search,
  Send,
  StrikethroughIcon,
  Trash,
  UnderlineIcon,
} from "lucide-react";

export const Icons = {
  eye: Eye,
  eyeOff: EyeOff,
  spinner: () => <Loader className="animate-spin" />,
  search: Search,
  likes: HeartIcon,
  trash: Trash,
  add: PlusIcon,
  image: Image,
  arrowLeft: MoveLeftIcon,

  bold: BoldIcon,
  strikeThrough: StrikethroughIcon,
  italic: ItalicIcon,
  underline: UnderlineIcon,
  paragraph: Pilcrow,
  bulletList: ListBulletIcon,
  orderedList: ListOrdered,
  codeBlock: Code2Icon,
  blockQuote: Quote,
  horizontalRule: DividerHorizontalIcon,

  posts: FileTextIcon,
  views: EyeIcon,
  comments: MessageCircleMore,
  send: Send,
};
